// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PinjamKelas.Api;

#nullable disable

namespace PinjamKelas.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260210063302_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PinjamKelas.Api.Models.Classroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("class_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_classrooms");

                    b.ToTable("classrooms", (string)null);
                });

            modelBuilder.Entity("PinjamKelas.Api.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("Expiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expiry");

                    b.Property<int>("IdClassroom")
                        .HasColumnType("integer")
                        .HasColumnName("id_classroom");

                    b.Property<int>("IdUsers")
                        .HasColumnType("integer")
                        .HasColumnName("id_users");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_posts");

                    b.HasIndex("IdClassroom")
                        .HasDatabaseName("ix_posts_id_classroom");

                    b.HasIndex("IdUsers")
                        .HasDatabaseName("ix_posts_id_users");

                    b.ToTable("posts", (string)null);
                });

            modelBuilder.Entity("PinjamKelas.Api.Models.StatusLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("IdClassroom")
                        .HasColumnType("integer")
                        .HasColumnName("id_classroom");

                    b.Property<DateTime>("LogTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("log_time");

                    b.HasKey("Id")
                        .HasName("pk_status_logs");

                    b.HasIndex("IdClassroom")
                        .HasDatabaseName("ix_status_logs_id_classroom");

                    b.ToTable("status_logs", (string)null);
                });

            modelBuilder.Entity("PinjamKelas.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("PinjamKelas.Api.Models.Post", b =>
                {
                    b.HasOne("PinjamKelas.Api.Models.Classroom", "Classroom")
                        .WithMany("Posts")
                        .HasForeignKey("IdClassroom")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_posts_classrooms_id_classroom");

                    b.HasOne("PinjamKelas.Api.Models.User", "User")
                        .WithMany("Posts")
                        .HasForeignKey("IdUsers")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_posts_users_id_users");

                    b.Navigation("Classroom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PinjamKelas.Api.Models.StatusLog", b =>
                {
                    b.HasOne("PinjamKelas.Api.Models.Classroom", "Classroom")
                        .WithMany("StatusLogs")
                        .HasForeignKey("IdClassroom")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_status_logs_classrooms_id_classroom");

                    b.Navigation("Classroom");
                });

            modelBuilder.Entity("PinjamKelas.Api.Models.Classroom", b =>
                {
                    b.Navigation("Posts");

                    b.Navigation("StatusLogs");
                });

            modelBuilder.Entity("PinjamKelas.Api.Models.User", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
